'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsSeguridad
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SeguridadSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Seguridad
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private InicioSessionporUsuarioWindowsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InicioSessionsinUsuarioWindowsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UsuarioWindowsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtenerPermisosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtenerResponsablesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ToXmlPerfilOperationCompleted As System.Threading.SendOrPostCallback
        
        Private VerificarPaginaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Facturas.My.MySettings.Default.Facturas_wsSeguridad_Seguridad
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event InicioSessionporUsuarioWindowsCompleted As InicioSessionporUsuarioWindowsCompletedEventHandler
        
        '''<remarks/>
        Public Event InicioSessionsinUsuarioWindowsCompleted As InicioSessionsinUsuarioWindowsCompletedEventHandler
        
        '''<remarks/>
        Public Event UsuarioWindowsCompleted As UsuarioWindowsCompletedEventHandler
        
        '''<remarks/>
        Public Event ObtenerPermisosCompleted As ObtenerPermisosCompletedEventHandler
        
        '''<remarks/>
        Public Event ObtenerResponsablesCompleted As ObtenerResponsablesCompletedEventHandler
        
        '''<remarks/>
        Public Event ToXmlPerfilCompleted As ToXmlPerfilCompletedEventHandler
        
        '''<remarks/>
        Public Event VerificarPaginaCompleted As VerificarPaginaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InicioSessionporUsuarioWindows", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InicioSessionporUsuarioWindows(ByVal cdSistema As Integer) As clsLogin
            Dim results() As Object = Me.Invoke("InicioSessionporUsuarioWindows", New Object() {cdSistema})
            Return CType(results(0),clsLogin)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InicioSessionporUsuarioWindowsAsync(ByVal cdSistema As Integer)
            Me.InicioSessionporUsuarioWindowsAsync(cdSistema, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InicioSessionporUsuarioWindowsAsync(ByVal cdSistema As Integer, ByVal userState As Object)
            If (Me.InicioSessionporUsuarioWindowsOperationCompleted Is Nothing) Then
                Me.InicioSessionporUsuarioWindowsOperationCompleted = AddressOf Me.OnInicioSessionporUsuarioWindowsOperationCompleted
            End If
            Me.InvokeAsync("InicioSessionporUsuarioWindows", New Object() {cdSistema}, Me.InicioSessionporUsuarioWindowsOperationCompleted, userState)
        End Sub
        
        Private Sub OnInicioSessionporUsuarioWindowsOperationCompleted(ByVal arg As Object)
            If (Not (Me.InicioSessionporUsuarioWindowsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InicioSessionporUsuarioWindowsCompleted(Me, New InicioSessionporUsuarioWindowsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InicioSessionsinUsuarioWindows", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InicioSessionsinUsuarioWindows(ByVal Usuario As String, ByVal Password As String, ByVal cdSistema As Integer) As clsLogin
            Dim results() As Object = Me.Invoke("InicioSessionsinUsuarioWindows", New Object() {Usuario, Password, cdSistema})
            Return CType(results(0),clsLogin)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InicioSessionsinUsuarioWindowsAsync(ByVal Usuario As String, ByVal Password As String, ByVal cdSistema As Integer)
            Me.InicioSessionsinUsuarioWindowsAsync(Usuario, Password, cdSistema, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InicioSessionsinUsuarioWindowsAsync(ByVal Usuario As String, ByVal Password As String, ByVal cdSistema As Integer, ByVal userState As Object)
            If (Me.InicioSessionsinUsuarioWindowsOperationCompleted Is Nothing) Then
                Me.InicioSessionsinUsuarioWindowsOperationCompleted = AddressOf Me.OnInicioSessionsinUsuarioWindowsOperationCompleted
            End If
            Me.InvokeAsync("InicioSessionsinUsuarioWindows", New Object() {Usuario, Password, cdSistema}, Me.InicioSessionsinUsuarioWindowsOperationCompleted, userState)
        End Sub
        
        Private Sub OnInicioSessionsinUsuarioWindowsOperationCompleted(ByVal arg As Object)
            If (Not (Me.InicioSessionsinUsuarioWindowsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InicioSessionsinUsuarioWindowsCompleted(Me, New InicioSessionsinUsuarioWindowsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UsuarioWindows", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UsuarioWindows() As Object
            Dim results() As Object = Me.Invoke("UsuarioWindows", New Object(-1) {})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UsuarioWindowsAsync()
            Me.UsuarioWindowsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UsuarioWindowsAsync(ByVal userState As Object)
            If (Me.UsuarioWindowsOperationCompleted Is Nothing) Then
                Me.UsuarioWindowsOperationCompleted = AddressOf Me.OnUsuarioWindowsOperationCompleted
            End If
            Me.InvokeAsync("UsuarioWindows", New Object(-1) {}, Me.UsuarioWindowsOperationCompleted, userState)
        End Sub
        
        Private Sub OnUsuarioWindowsOperationCompleted(ByVal arg As Object)
            If (Not (Me.UsuarioWindowsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UsuarioWindowsCompleted(Me, New UsuarioWindowsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPermisos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtenerPermisos(ByVal oLogin As clsLogin) As Permisos
            Dim results() As Object = Me.Invoke("ObtenerPermisos", New Object() {oLogin})
            Return CType(results(0),Permisos)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtenerPermisosAsync(ByVal oLogin As clsLogin)
            Me.ObtenerPermisosAsync(oLogin, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtenerPermisosAsync(ByVal oLogin As clsLogin, ByVal userState As Object)
            If (Me.ObtenerPermisosOperationCompleted Is Nothing) Then
                Me.ObtenerPermisosOperationCompleted = AddressOf Me.OnObtenerPermisosOperationCompleted
            End If
            Me.InvokeAsync("ObtenerPermisos", New Object() {oLogin}, Me.ObtenerPermisosOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtenerPermisosOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtenerPermisosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtenerPermisosCompleted(Me, New ObtenerPermisosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerResponsables", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtenerResponsables(ByVal cdSistema As Integer, ByVal strXml As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ObtenerResponsables", New Object() {cdSistema, strXml})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtenerResponsablesAsync(ByVal cdSistema As Integer, ByVal strXml As String)
            Me.ObtenerResponsablesAsync(cdSistema, strXml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtenerResponsablesAsync(ByVal cdSistema As Integer, ByVal strXml As String, ByVal userState As Object)
            If (Me.ObtenerResponsablesOperationCompleted Is Nothing) Then
                Me.ObtenerResponsablesOperationCompleted = AddressOf Me.OnObtenerResponsablesOperationCompleted
            End If
            Me.InvokeAsync("ObtenerResponsables", New Object() {cdSistema, strXml}, Me.ObtenerResponsablesOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtenerResponsablesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtenerResponsablesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtenerResponsablesCompleted(Me, New ObtenerResponsablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ToXmlPerfil", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ToXmlPerfil(ByVal arr() As Integer) As String
            Dim results() As Object = Me.Invoke("ToXmlPerfil", New Object() {arr})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ToXmlPerfilAsync(ByVal arr() As Integer)
            Me.ToXmlPerfilAsync(arr, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ToXmlPerfilAsync(ByVal arr() As Integer, ByVal userState As Object)
            If (Me.ToXmlPerfilOperationCompleted Is Nothing) Then
                Me.ToXmlPerfilOperationCompleted = AddressOf Me.OnToXmlPerfilOperationCompleted
            End If
            Me.InvokeAsync("ToXmlPerfil", New Object() {arr}, Me.ToXmlPerfilOperationCompleted, userState)
        End Sub
        
        Private Sub OnToXmlPerfilOperationCompleted(ByVal arg As Object)
            If (Not (Me.ToXmlPerfilCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ToXmlPerfilCompleted(Me, New ToXmlPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarPagina", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VerificarPagina(ByVal dsNombrePantalla As String, ByVal oPermisos As System.Xml.XmlNode) As Boolean
            Dim results() As Object = Me.Invoke("VerificarPagina", New Object() {dsNombrePantalla, oPermisos})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VerificarPaginaAsync(ByVal dsNombrePantalla As String, ByVal oPermisos As System.Xml.XmlNode)
            Me.VerificarPaginaAsync(dsNombrePantalla, oPermisos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VerificarPaginaAsync(ByVal dsNombrePantalla As String, ByVal oPermisos As System.Xml.XmlNode, ByVal userState As Object)
            If (Me.VerificarPaginaOperationCompleted Is Nothing) Then
                Me.VerificarPaginaOperationCompleted = AddressOf Me.OnVerificarPaginaOperationCompleted
            End If
            Me.InvokeAsync("VerificarPagina", New Object() {dsNombrePantalla, oPermisos}, Me.VerificarPaginaOperationCompleted, userState)
        End Sub
        
        Private Sub OnVerificarPaginaOperationCompleted(ByVal arg As Object)
            If (Not (Me.VerificarPaginaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VerificarPaginaCompleted(Me, New VerificarPaginaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsLogin
        
        Private userField As String
        
        Private passField As String
        
        Private strDomainField As String
        
        Private cdAreaField As Integer
        
        Private strAreaField As String
        
        Private cdRespField As Integer
        
        Private nombreField As String
        
        Private nombreCompletoField As String
        
        Private apellidoField As String
        
        Private esUsuarioNTField As Boolean
        
        Private blLoggedField As Boolean
        
        Private cdSistemaField As Integer
        
        Private cdUsuarioField As Integer
        
        Private xmlPermisosField As System.Xml.XmlNode
        
        Private mensajeField As String
        
        Private dsEmailField As String
        
        Private sessionIDField As String
        
        Private cdEstadoField As Integer
        
        Private rowGuidField As String
        
        Private cdEdificioField As Integer
        
        '''<comentarios/>
        Public Property User() As String
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Pass() As String
            Get
                Return Me.passField
            End Get
            Set
                Me.passField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property strDomain() As String
            Get
                Return Me.strDomainField
            End Get
            Set
                Me.strDomainField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property cdArea() As Integer
            Get
                Return Me.cdAreaField
            End Get
            Set
                Me.cdAreaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property strArea() As String
            Get
                Return Me.strAreaField
            End Get
            Set
                Me.strAreaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property cdResp() As Integer
            Get
                Return Me.cdRespField
            End Get
            Set
                Me.cdRespField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NombreCompleto() As String
            Get
                Return Me.nombreCompletoField
            End Get
            Set
                Me.nombreCompletoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property EsUsuarioNT() As Boolean
            Get
                Return Me.esUsuarioNTField
            End Get
            Set
                Me.esUsuarioNTField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property blLogged() As Boolean
            Get
                Return Me.blLoggedField
            End Get
            Set
                Me.blLoggedField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property cdSistema() As Integer
            Get
                Return Me.cdSistemaField
            End Get
            Set
                Me.cdSistemaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property cdUsuario() As Integer
            Get
                Return Me.cdUsuarioField
            End Get
            Set
                Me.cdUsuarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property xmlPermisos() As System.Xml.XmlNode
            Get
                Return Me.xmlPermisosField
            End Get
            Set
                Me.xmlPermisosField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property dsEmail() As String
            Get
                Return Me.dsEmailField
            End Get
            Set
                Me.dsEmailField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SessionID() As String
            Get
                Return Me.sessionIDField
            End Get
            Set
                Me.sessionIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property cdEstado() As Integer
            Get
                Return Me.cdEstadoField
            End Get
            Set
                Me.cdEstadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RowGuid() As String
            Get
                Return Me.rowGuidField
            End Get
            Set
                Me.rowGuidField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property cdEdificio() As Integer
            Get
                Return Me.cdEdificioField
            End Get
            Set
                Me.cdEdificioField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsPermiso
        
        Private dsPermisoField As String
        
        Private cdPermisoField As String
        
        Private elementosField() As clsPermiso
        
        '''<comentarios/>
        Public Property dsPermiso() As String
            Get
                Return Me.dsPermisoField
            End Get
            Set
                Me.dsPermisoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property cdPermiso() As String
            Get
                Return Me.cdPermisoField
            End Get
            Set
                Me.cdPermisoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Elementos() As clsPermiso()
            Get
                Return Me.elementosField
            End Get
            Set
                Me.elementosField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Permisos
        
        Private permisos1Field() As clsPermiso
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute("Permisos")>  _
        Public Property Permisos1() As clsPermiso()
            Get
                Return Me.permisos1Field
            End Get
            Set
                Me.permisos1Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub InicioSessionporUsuarioWindowsCompletedEventHandler(ByVal sender As Object, ByVal e As InicioSessionporUsuarioWindowsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InicioSessionporUsuarioWindowsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsLogin
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsLogin)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub InicioSessionsinUsuarioWindowsCompletedEventHandler(ByVal sender As Object, ByVal e As InicioSessionsinUsuarioWindowsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InicioSessionsinUsuarioWindowsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsLogin
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsLogin)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub UsuarioWindowsCompletedEventHandler(ByVal sender As Object, ByVal e As UsuarioWindowsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UsuarioWindowsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ObtenerPermisosCompletedEventHandler(ByVal sender As Object, ByVal e As ObtenerPermisosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtenerPermisosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Permisos
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Permisos)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ObtenerResponsablesCompletedEventHandler(ByVal sender As Object, ByVal e As ObtenerResponsablesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtenerResponsablesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ToXmlPerfilCompletedEventHandler(ByVal sender As Object, ByVal e As ToXmlPerfilCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ToXmlPerfilCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub VerificarPaginaCompletedEventHandler(ByVal sender As Object, ByVal e As VerificarPaginaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VerificarPaginaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
